pribt( hello world)
print(nama saya nurul)
print(saya dari kelas x rkj 1)
print(saya sekolah di harapan bangsa)
print(saya adalah fans V BTS)
PRINT(umur saya 15 tahun)
peiny(saya berasal dari SMPN 8 DEPOK)
print(hobi saya adala kberenang dan bermain piano )
print(cita cita saya menjadi diplomat )
print(terimakasih)